# Generated by Django 5.0.6 on 2024-05-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('Message', models.TextField()),
                ('picture', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
